{% set name = "CairoSVG" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 432531d72347291b9a9ebfb6777026b607563fd8719c46ee742db0aef7271ba0

build:
  number: 1
  noarch: python
  entry_points:
    - cairosvg = cairosvg.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - pytest-runner
  run:
    - python >=3.5
    - cairocffi
    - cssselect2
    - pillow
    - tinycss2
    - defusedxml

test:
  requires:
    - git
    - pip
  imports:
    - cairosvg
  commands:
    - cairosvg --help
    - git clone --single-branch --branch {{ version }} https://github.com/Kozea/CairoSVG.git
    - cd CairoSVG/test_non_regression/svg # Needed for SVGs that use relative paths
    - find ./ -maxdepth 1 -type f -name '*.svg' -exec echo {} \; -exec cairosvg -u {} -o {}.png \;
    - find ./ -maxdepth 1 -type f -name '*.svg' -exec test ! -s {}.png \; -exec touch a_test_failed \;
    - test ! -e a_test_failed
#    - cairosvg CairoSVG/test_non_regression/svg/toap04.svg -o test.png
#    - test -s test.png
    # - for %%v in (*.svg) do (echo ./%%v & cairosvg -u "./%%v" -o "./%%v.png")
    # - for %%v in (*.svg) do test -s "./%%v.png"

about:
  home: http://www.cairosvg.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: A Simple SVG Converter based on Cairo
  doc_url: http://www.cairosvg.org/documentation
  dev_url: https://github.com/Kozea/CairoSVG

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
