{% set name = "CairoSVG" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 432531d72347291b9a9ebfb6777026b607563fd8719c46ee742db0aef7271ba0

build:
  number: 1
  noarch: python
  entry_points:
    - cairosvg = cairosvg.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >={{ python_min }}
    - cairocffi
    - cssselect2
    - pillow
    - tinycss2
    - defusedxml

test:
  requires:
    - python {{ python_min }}
  imports:
    - cairosvg
  commands:
    - cairosvg --help

about:
  home: http://www.cairosvg.org/
  license: 	LGPL-3.0-only
  license_file: LICENSE
  summary: A Simple SVG Converter based on Cairo
  doc_url: http://www.cairosvg.org/documentation
  dev_url: https://github.com/Kozea/CairoSVG

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
