{% set name = "CairoSVG" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e668f96653326780036ebb0a9ff2bb59a8443d7bcfc51a14aab77b57a8e67ad

build:
  number: 1
  entry_points:
    - cairosvg = cairosvg.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - pytest-runner
  run:
    - python >=3.5
    - cairocffi
    - cssselect2
    - pillow
    - tinycss2
    - defusedxml

test:
  imports:
    - cairosvg
  commands:
    - cairosvg --help

about:
  home: http://www.cairosvg.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A Simple SVG Converter based on Cairo'
  doc_url: http://www.cairosvg.org/documentation
  dev_url: https://github.com/Kozea/CairoSVG

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
