{% set name = "CairoSVG" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: d60fe75c238ffba3f8e21e06dad8727ecd2bcef8d3d55fc11f9286c08c5cc710

build:
  number: 0
  noarch: python
  entry_points:
    - cairosvg = cairosvg.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >={{ python_min }}
    - cairocffi
    - cssselect2
    - pillow
    - tinycss2
    - defusedxml

test:
  requires:
    - python {{ python_min }}
  imports:
    - cairosvg
  commands:
    - cairosvg --help

about:
  home: http://www.cairosvg.org/
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: A Simple SVG Converter based on Cairo
  doc_url: http://www.cairosvg.org/documentation
  dev_url: https://github.com/Kozea/CairoSVG

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
