{% set name = "CairoSVG" %}
{% set version = "1.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f66e0f3a2711d2e36952bb370fcd45837bfedce2f7882935c46c45c018a21557

build:
  number: 0
  noarch: python
  entry_points:
    - cairosvg = cairosvg.__init__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python <3
    - pip
    - pytest-runner
  run:
    - python <3
    - pycairo
    - cairocffi
    - cssselect2
    - pillow
    - tinycss2
    - defusedxml

test:
  imports:
    - cairosvg
  commands:
    - cairosvg --help

about:
  home: http://www.cairosvg.org/
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: 'A Simple SVG Converter based on Cairo'
  doc_url: http://www.cairosvg.org/documentation
  dev_url: https://github.com/Kozea/CairoSVG

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
