schema_version: 1

context:
  name: CairoSVG
  version: "2.9.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | lower }}-${{ version }}.tar.gz
  sha256: 1debb00cd2da11350d8b6f5ceb739f1b539196d71d5cf5eb7363dbd1bfbc8dc5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - cairosvg = cairosvg.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >=${{ python_min }}
    - cairocffi
    - cssselect2
    - pillow
    - tinycss2
    - defusedxml

tests:
  - python:
      imports:
        - cairosvg
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - cairosvg --help

about:
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: A Simple SVG Converter based on Cairo
  homepage: http://www.cairosvg.org/
  repository: https://github.com/Kozea/CairoSVG
  documentation: http://www.cairosvg.org/documentation

extra:
  recipe-maintainers:
    - johanneskoester
    - carlodri
